# Generated by Django 3.1.5 on 2021-03-22 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(choices=[('HAPPY', 'HAPPY'), ('ANGRY', 'ANGRY'), ('SUPRISE', 'SUPRISE'), ('NEUTRAL', 'NEUTRAL')], default='NEUTRAL', max_length=200)),
                ('link', models.CharField(default='NO LINK', max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.memecategory')),
            ],
        ),
    ]
