# Generated by Django 3.1.5 on 2021-03-21 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210319_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='link',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='.\\api\\images\\'),
        ),
    ]
